language: c
compiler: gcc

before_install:
  # GENERATE FILES FOR EFFICIENCY TESTS
  - cd efficiencyTests/data
  - chmod +x ./generateData.sh
  - ./generateData.sh
  # Get back to source folder
  - cd ../../

install:
  - sudo apt-get install g++-multilib

script:
  # RUN ALL UNIT TESTS
  - cd tests/
  - make AllTests
  # RUN EFFICIENCY TESTS
  - cd ../efficiencyTests/
  - make EfficiencyTests
  # RUN GPROF ANALYSIS
  - make GprofTest && cat ./profile-data.txt
  # RUN VALGRIND ANALYSIS
