language: c
compiler: gcc

before_install:
  - sudo apt-get install g++-multilib

script:
  # RUN ALL UNIT TESTS
  - cd project/tests
  - make AllTests
  # RUN EFFICIENCY TESTS
  - cd ../efficiencyTests/
  - make EfficiencyTests
  # RUN GPROF ANALYSIS
  - make GprofTest
  # RUN VALGRIND ANALYSIS
