language: c
compiler: gcc

before_install:
  # GENERATE FILES FOR EFFICIENCY TESTS
  - cd project/efficiencyTests/
  - mkdir data && cd ./data/
  # 1 GB files
  - dd if=/dev/urandom of=firstNumber1GB bs=1024 count=1048576
  - dd if=/dev/urandom of=secondNumber1GB bs=1024 count=1048576
  # 1 MB file
  - dd if=/dev/urandom of=firstNumber1MB bs=1024 count=1024
  # 20 KB file
  - dd if=/dev/urandom of=firstNumber20KB bs=1024 count=20
  # Get back to source folder
  - cd ../../../

install:
  - sudo apt-get install g++-multilib

script:
  # RUN ALL UNIT TESTS
  - cd project/tests
  - make AllTests
  # RUN EFFICIENCY TESTS
  - cd ../efficiencyTests/
  - make EfficiencyTests
  # RUN GPROF ANALYSIS
  - make GprofTest && cat ./profile-data.txt
  # RUN VALGRIND ANALYSIS
